apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: https://hub.docker.com/repository/docker/mahesht2000/personal_project/myapp:latest
        ports:
        - containerPort: 80